spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vocab_ease?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9091
  servlet:
    context-path: /api
project:
  folder: D:/IdeaProject/VocabEase/
log:
  root:
    level: debug
isDev:
  false
mybatis:
  mapper-locations: classpath*:com/javastudy/vocabease_common/mappers/*.xml
  type-aliases-package: com.javastudy.vocabease_common.entity
  configuration:
    map-underscore-to-camel-case: true